# fly.toml app configuration file generated for tkpd-skipper-hackathon on 2023-10-04T18:45:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tkpd-skipper-hackathon"
primary_region = "sin"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
