# Skipper Framework
# Created date: 4/10/2023

version: '3'
services:
  skipper-app:
    image: $REGISTRY_SERVER/web-ui-hackathon:$GIT_COMMIT
    restart: always
    volumes:
      - ${PWD}/.env:/code/.env
    ports:
      - $KRATOS_PORT:3000
    networks:
      - br0-docker-feature
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'

networks:
  br0-docker-feature:
    external: true
